# Generated by Django 2.0.2 on 2018-03-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('room_number', models.IntegerField(default='-1')),
                ('is_occupied', models.BooleanField(default=True)),
            ],
        ),
    ]
