# Generated by Django 2.0.2 on 2018-04-10 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('senior_des', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='room_number',
        ),
        migrations.AddField(
            model_name='rooms',
            name='timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
