# Generated by Django 2.0.2 on 2018-04-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_des', '0002_auto_20180410_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=10)),
                ('occupied', models.BooleanField(default=True)),
            ],
        ),
    ]
